# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "courses-terraform-terragrunt-states-bucket-new"
    dynamodb_table = "courses-lock-table"
    encrypt        = true
    key            = "eu-north-1/./terraform.tfvars"
    profile        = "default"
    region         = "eu-north-1"
  }
}
